export const translations = {
    en: {
        app_name: "Tawsyah",
        home: "Home",
        watchlist: "Watchlist",
        favorites: "Favorites",
        ai_recommendation: "AI Recommendation",
        login: "Login",
        signup: "Sign Up",
        logout: "Logout",
        trending: "Trending Movies",
        search: "Search for a movie...",
        add_watchlist: "Watch Later",
        added_watchlist: "Added to Watchlist",
        add_favorite: "Favorite",
        added_favorite: "Favorited",
        get_recommendations: "Get Recommendations",
        similar_movies: "Because you liked ",
        no_movies: "No movies found.",
        email: "Email Address",
        password: "Password",
        name: "Full Name",
        welcome: "Welcome to Tawsyah",
        hero_subtitle: "Discover your next favorite movie with our AI-powered recommendation system.",
        start_exploring: "Start Exploring",
        loading: "Loading...",
        error: "An error occurred. Please try again later."
    },
    ar: {
        app_name: "توصية",
        home: "الرئيسية",
        watchlist: "قائمة المشاهدة",
        favorites: "المفضلة",
        ai_recommendation: "توصيات الذكاء الاصطناعي",
        login: "تسجيل الدخول",
        signup: "إنشاء حساب",
        logout: "تسجيل الخروج",
        trending: "الأفلام الرائجة",
        search: "ابحث عن فيلم...",
        add_watchlist: "مشاهدة لاحقاً",
        added_watchlist: "في قائمة المشاهدة",
        add_favorite: "إضافة للمفضلة",
        added_favorite: "في المفضلة",
        get_recommendations: "احصل على توصيات",
        similar_movies: "لأنك أحببت ",
        no_movies: "لم يتم العثور على أفلام.",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        name: "الاسم الكامل",
        welcome: "مرحباً بك في توصية",
        hero_subtitle: "اكتشف فيلمك المفضل القادم مع نظام التوصيات الذكي الخاص بنا.",
        start_exploring: "ابدأ الاستكشاف",
        loading: "جاري التحميل...",
        error: "حدث خطأ. يرجى المحاولة مرة أخرى لاحقاً."
    }
};
